BoxLayoutExample:
<BoxLayoutExample>:
    orientation: "horizontal"
    Button:
        text: "A"
        #size; "40dp","40dp"
        size_hint: .8,.5
        #pos_hint: {"x": .1}
        #pos_hint: {"right": .3}
        pos_hint: {"center_x": .5}
    Button:
        text: "B"
        size_hint: 1,.5
        #pos_hint: {"top": 1}
        pos_hint: {"center_y": .5}
    Button:
        text: "C"
        size_hint: 1,None
        height: "60dp"